title: Cooperativa Kapé R.L.
email: tu-email@ejemplo.com
description: "Impulsando el Futuro Agrícola de Tamahú."
baseurl: "" # Para Netlify, esto debe estar vacío.
url: "https://tu-dominio.netlify.app" # Reemplaza esto con la URL de tu sitio en Netlify
future: true
twitter_username: jekyllrb
github_username: jekyll
permalink: /:categories/:title/

# Añade la siguiente línea para asegurarte de que la carpeta admin se incluya.
include: ['admin']

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
collections:
  servicios:
    output: true
    permalink: /:collection/:name/
