[build]
  command = "jekyll build"
  publish = "_site"

[[redirects]]
  from = "/.netlify/identity"
  to = "/admin"
  status = 200

[[redirects]]
  from = "/*"
  to = "/admin"
  status = 200
  force = false
