backend:
  name: git-gateway
  branch: main # o la rama que uses

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "Noticias"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "single-post"}
      - {label: "Título de la Noticia", name: "title", widget: "string", required: true}
      - {label: "Autor", name: "author", widget: "string", default: "Cooperativa KAPÉ R.L."}
      - {label: "Fecha", name: "date", widget: "datetime", required: true}
      - {label: "Imagen de Portada", name: "image", widget: "image", required: true}
      - {label: "Resumen", name: "excerpt", widget: "text", required: true}
      - {label: "Contenido", name: "body", widget: "markdown", required: true}
      
  - name: "servicios"
    label: "Servicios"
    folder: "_servicios"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "single-post"}
      - {label: "Título Corto del Servicio", name: "title", widget: "string", required: true}
      - {label: "Título Completo", name: "main_title", widget: "string", required: true}
      - {label: "URL del Servicio (Ej: creditos-agricolas)", name: "permalink", widget: "string", required: true}
      - {label: "Imagen de Portada", name: "image", widget: "image", required: true}
      - {label: "Resumen", name: "excerpt", widget: "text", required: true}
      - {label: "Contenido", name: "body", widget: "markdown", required: true}
